---
# file: mod_wsgi/tasks/main.yml
#
# tasks file
#

- include: debug.yml
  when: debug | default(false)
  tags: debug

- include: validation.yml
  tags: validation

- include: "{{ mod_wsgi_installation }}/main.yml"
  tags: installation

- name: scripts | setup
  template:
    src=var/www/wsgi/script.wsgi.j2
    dest="{{ mod_wsgi_dir_install }}/{{ item.name }}.wsgi"
    owner="{{ httpd_user }}"
    group="{{ httpd_user }}"
    mode=0644
  become: yes
  with_items: "{{ mod_wsgi_scripts }}"
  when: mod_wsgi_use_httpd is defined and
        mod_wsgi_use_httpd
