---
# file: mod_wsgi/tasks/main.yml
#
# tasks file
#

- include: debug.yml
  when: debug | default(false)
  tags: debug

- include: validation.yml
  tags: validation

- include: "{{ httpd_installation }}/main.yml"
  tags: installation
